import { Box } from "@codecademy/gamut";
import { GlobalHeaderProps, GlobalPage } from "@codecademy/gamut-labs";
import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  const footer = {
    onClick: () => {}, // todo
    userGeo: "unknown", // TODO INDIA DETECTION
  };
  const header: GlobalHeaderProps = {
    action: () => {}, // todo
    search: {
      onEnable: () => {},
      onSearch: () => {},
      onTrackingClick: () => {},
    },
    type: "loading",
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <GlobalPage footer={footer} header={header}>
        hello world!
        <Box bg="pink-400">yo</Box>
      </GlobalPage>
    </>
  );
};

export default Home;
